@startuml
title Use Case Diagram - Sistema Ticketing Cinema

actor Cliente
actor SistemaInformatico
actor Banca

usecase "Ticketing Cinema" as UC1 
usecase "Check Sistema" as UC2
usecase "Pagamento" as UC3

' Relazioni attori '
  Cliente --> (Seleziona film)
  Cliente --> (Seleziona spettacolo)
  Cliente --> (Verifica disponibilità)
  Cliente --> (Seleziona posto)
  Cliente --> (Acquista biglietto)
  Cliente --> (Riceve notifica disponibilità)

(Seleziona posto) .> (Verifica disponibilità) : <<include>>
(Riceve notifica disponibilità) .> (Verifica disponibilità) : <<extend>>

@enduml
